spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/stockdb
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

app:
  ai:
    summary-enabled: true
    summary-cache-key-prefix: "ai-summary:"
  finnhub:
    api-key: d7om391r01qsb7bfek20d7om391r01qsb7bfek2g
    base-url: https://finnhub.io/api/v1
